name: "AxSellChest"
main: "com.artillexstudios.axsellchest.AxSellChestPlugin"
version: "$version"
api-version: "1.18"
folia-supported: true
softdepend:
  - RoseStacker
  - WildStacker
  - ShopGUIPlus
  - Vault
  - SuperiorSkyBlock2
  - zShop
  - EconomyShopGUI
  - BentoBox
  - EconomyShopGUI-Premium
  - AxGens