name: "AxSellChest"
main: "com.artillexstudios.axsellchest.AxSellChestPlugin"
version: "$version"
api-version: "1.18"

softdepend:
  - RoseStacker
  - WildStacker
  - ShopGUIPlus
  - Vault
  - SuperiorSkyBlock2