# The type of the block
block: "chest"
# The multiplier of this chest
booster: 1.0

options:
  sell-interval: 10 # Is in ticks
  auto-sell: true
  collect-chunk: true
  delete-unsellable: true
  hologram: true
  bank: true
  charge: true
  # In minutes
  max-charge: 1440

inventory:
  title: "<green><owner>'s</green> <white>default sellchest"
  size: 45 # Must be divisible by 9
  items:
    - type: "stone"
      name: ""
      lore:
        - ""
      actions:
        - "[close]"
      slots:
        - "1-10"
        - "12"
    - type: "gold_block"
      name: "Bank: <bank>"
      lore:
        - ""
        - "Click to toggle!"
      actions:
        - "[toggle] bank"
        - "[close]"
      slots:
        - "13"

hologram:
  height: 1.5
  content:
    - ""
    - ""
    - ""
    - ""

item:
  name: ""
  type: "chest"
  lore:
    - ""
    - ""
    - ""